### ISSUE TITLE
Controlling the version when installing as `package`?

### ISSUE THREAD

**Issue by eyalzek** [chef-cookbooks/chef_nginx#100]
### Cookbook version
6.0.2

### Chef-client version
12.19.36

### Platform Details
Ubuntu 14.04

### Scenario:
Upgrade `nginx` package version. After the package has been installed for the first time on the node (whether it be manually or with chef), the version of the package is fixed and there is no way to upgrade it anymore using this cookbook without manual intervention.

### Steps to Reproduce:
1. `include_recipe 'chef_nginx'` without setting any attribute - the distro version of nginx would be installed, in my case `1.4.6`.
2. set `node.default['nginx']['repo_source'] = 'nginx'` and run the recipe on the same node again.

### Expected Result:
`nginx` package would be upgraded, either by the version specified by `node['nginx']['version']`, or by installing the version available from the new source.

### Actual Result:
The nginx repository is added as a source, but the package is not installed, leading to this:

```
nginx:
  Installed: 1.4.6-1ubuntu3.7
  Candidate: 1.12.0-1~trusty
  Version table:
     1.12.0-1~trusty 0
        500 http://nginx.org/packages/ubuntu/ trusty/nginx amd64 Packages
     1.10.3-1~trusty 0
        500 http://nginx.org/packages/ubuntu/ trusty/nginx amd64 Packages
     1.10.2-1~trusty 0
        500 http://nginx.org/packages/ubuntu/ trusty/nginx amd64 Packages
     1.10.1-1~trusty 0
        500 http://nginx.org/packages/ubuntu/ trusty/nginx amd64 Packages
     1.10.0-1~trusty 0
        500 http://nginx.org/packages/ubuntu/ trusty/nginx amd64 Packages
     1.8.1-1~trusty 0
        500 http://nginx.org/packages/ubuntu/ trusty/nginx amd64 Packages
     1.8.0-1~trusty 0
        500 http://nginx.org/packages/ubuntu/ trusty/nginx amd64 Packages
 *** 1.4.6-1ubuntu3.7 0
        500 http://eu-central-1a.clouds.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.4.6-1ubuntu3 0
        500 http://eu-central-1a.clouds.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```
also, going into chef-shell to check the version I see this: 

```
chef (12.19.36)> node['nginx']['version']
 => "1.4.6" 
```

I realize that `node['nginx']['version']` is used only for source installation, but I really don't understand why? what control does this cookbook give me over the `nginx` installation on my nodes if I cannot perform package upgrades?

**Comment by tas50** [comment]
Upgrades are not a scenario for this cookbook. In general we shy away from upgrades in Chef recipes since that would cause outages as nodes automatically upgrades and restarted nginx when a new version became available. It's a scary thing to do. If you want to specify an upgrade to a specific version once the repo is setup that's pretty easy to do in a simple wrapper cookbook. Just use the package resource.
