### ISSUE TITLE
Cannot define nginx stream blocks

### ISSUE THREAD

**Issue by poblahblahblah** [chef-cookbooks/chef_nginx#104]
### Cookbook version
6.1.1

### Chef-client version
12.19.36

### Platform Details
CentOS/RHEL 6 and 7
Ubuntu 14.04 and 16.04

### Scenario:
I would like to use nginx as a TCP load balancer although if I use the `nginx_site` nginx fails to restart because `/etc/nginx/sites-enabled` is included within the `http` context block. According to nginx `stream` should be defined in the main context, not within `http`.

### Steps to Reproduce:
Create an nginx site with this configuration:
```
stream {

  upstream dataserver {
    zone dataserver 512k;
    server localhost:8443;
  }

  match dataserver_up {
    send      "GET /status.txt HTTP/1.0\r\nHost: localhost\r\n\r\n";
    expect ~* "dataserver:up";
  }

  server {
    listen       443;
    health_check fails=3 passes=3 interval=2s match=dataserver_up;
    proxy_pass   dataserver;
  }

}
```

### Expected Result:
I expected this would fail, although there does not appear to be an "official" way with this cookbook to define any streams. As a hack I lifted the nginx.conf.erb template from this cookbook, dropped it in our wrapper cookbook and added a block at the very bottom, outside of the `http` context:

```
include /etc/nginx/streams-enabled/*;
```

### Actual Result:
nginx fails to restart or reload.

**Comment by tas50** [comment]
Any idea how this is handled in Debian? sites-enabled is a debian-ism that the NGINX folks really don't like. They'd prefer we shove it all into the conf folder.

**Comment by poblahblahblah** [comment]
It looks like NGINX's recommended way might be to remove the include directives out of the http context block: https://www.nginx.com/resources/admin-guide/configuration-files/

I think this would require every config to set it's context, which would break a lot of sites if this cookbook was updated to follow that standard.

As for Debian, Looking at the version that ships with Jessie, it doesn't appear that Debian nginx package maintainers handle this scenario. The include directives are all within the `http` context. They do have a separate commented out block for the `mail` context, but no include directive within that.

**Comment by iennae** [comment]
Hi,

This cookbook will be deprecated in favor of the nginx cookbook. https://github.com/chef-cookbooks/nginx. If this is still an issue for you please open up an issue on that cookbook https://github.com/chef-cookbooks/nginx/issues.

Thanks.
