### ISSUE TITLE
Missing snippets directory

### ISSUE THREAD

**Issue by dbudwin** [chef-cookbooks/chef_nginx#105]
### Cookbook version
6.1.1

### Chef-client version
Chef Development Kit Version: 1.3.43
chef-client version: 12.19.36
delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
berks version: 5.6.4
kitchen version: 1.16.0

### Platform Details
macOS 10.12.5

### Scenario:
When using the default Nginx cookbook, when I converge an Ubuntu 16.04 node I expect the directory `etc/nginx/snippets` to exist with `snakeoil.conf` and `fastcgi-php.conf`.

See here for Nginx's expected directory structure: https://wiki.debian.org/Nginx/DirectoryStructure#A.2Fetc.2Fnginx.2F

### Steps to Reproduce:

1. `chef generate cookbook TestNginxChef`
2. Edit `metadata.rb` to add `depends 'chef_nginx', '~> 6.1.1'`
3. Edit `default/recipes` to add `include_recipe 'chef_nginx::default'`
4. Execute `kitchen converge`
5. Execute `kitchen login`
6. `cd` to `/etc/nginx`
7. Execute `ls` and note the lack of a `snippets` directory

### Expected Result:

There should be a `snippets` directory as part of the default Nginx configuration which is needed for using PHP's Fast-CGI option.

### Actual Result:

No `snippets` directory exists.

**Comment by iennae** [comment]
When I install nginx from the package (not via chef) it does not have a snippets directory. The documentation you are pointing to is not nginx specific, it's debian specific. I suspect that current versions of nginx doesn't include the snippets. Please check to see if the version of nginx you are using doesn't have the snippets directory anymore.

**Comment by dbudwin** [comment]
I'm experiencing different functionality, and just to confirm my experience, I make a brand new vagrant box from Atlas.

In a new, local empty directory I ran:

`vagrant init ubuntu/xenial64; vagrant up --provider virtualbox`

Then I logged into the box using `vagrant ssh`.  Once logged in, I performed a `which nginx` to confirm Nginx was not installed yet.  Then I executed `sudo apt-get install nginx`.  After it installed, I executed `cd /etc/nginx`.  I ran `ls` and there is a `snippets` directory.  I `cd snippets` and ran `ls` to confirm the `snakeoil.conf` and `fastcgi-php.conf` files existed as expected.

![image](https://user-images.githubusercontent.com/15161181/27522698-0d09e73c-59f6-11e7-8937-1df008fe5631.png)

**Comment by iennae** [comment]
Did you set up the nginx repo?

**Comment by dbudwin** [comment]
> Did you set up the nginx repo?

What do you mean?  I didn't  do anything "fancy" per se.  I *assumed* (and this could be my problem) that the default Nginx cookbook will install from `apt`.

**Comment by iennae** [comment]
This cookbook uses the Nginx.org Repository installation. It looks like you might be pulling from the Ubuntu packages which probably have been packaged slightly differently.

**Comment by dbudwin** [comment]
Thanks for the help!  The documentation does describe that it uses Nginx's repo and not the distro's repo, I just missed that part.  Setting `default['nginx']['repo_source'] = nil` and adding `apt_update` as the first line in `default.rb` installs Nginx the way I'm used to (and the way most tutorials I've seen regarding Nginx and Fast CGI expect it to be set up).

**Comment by iennae** [comment]
Thanks for sharing the fix!
