### ISSUE TITLE
split off chef_nginx::repo recipe

### ISSUE THREAD

**Issue by haidangwa** [chef-cookbooks/chef_nginx#108]
We've been using the other yum-* cookbooks to configure various yum repos on our nodes. We wrap those cookbooks with our own attribute values that point the repo URL to our internal yum repos. We'd like to be able to do the same for nginx, but adding a dependency on this cookbook is an overburden for all the other features that this cookbook provides. We also have teams that may want to use this cookbook to configure their nginx installations.  By creating a wrapper cookbook of our own that sets the attributes for the nginx repo, this cookbook would have its own dependency constraint on chef_nginx. There's a chance that we could have colliding dependency constraints if those other teams use our wrapper to setup their yum configuration and also try to use chef_nginx to configure nginx itself.

We think this cookbook diverges from the precedent already set by the other yum-* cookbooks available in the supermarket; whereby those cookbooks only configure yum for particular repos. I would like to see  the yum portion of the repo recipe separated out into a separate cookbook.

**Comment by iennae** [comment]
Thanks for asking about this. We appreciate that there are other yum-* cookbooks but the pattern of creating microservices for each of the applications is not a sustainable one so we will be leaving the recipe as is. You are more than welcome to create separate cookbooks and share them with the community.
