### ISSUE TITLE
Non-existent apt source configured on Raspbian

### ISSUE THREAD

**Issue by PierreBeucher** [chef-cookbooks/chef_nginx#109]
### Cookbook version

6.1.1

### Chef-client version

13.3.42

### Platform Details

Raspbian

### Scenario:

On Debian platform family, an apt source file `nginx.list` is created with `http://nginx.org/packages/#{node['platform']}`. This results as `http://nginx.org/packages/raspbian` on Raspbian, however it does not exists (`http://nginx.org/packages/debian` works just fine)

### Steps to Reproduce:

Run this cookbook on Raspberry PI with Raspbian

### Expected Result:

Sucessful chef-client run with proper apt source.

### Actual Result:

The chef-client fails when running apt: source `http://nginx.org/packages/raspbian` does not exists.

**Comment by PierreBeucher** [comment]
A workaround is to add the following attribute in your cookbook:

`default['nginx']['upstream_repository'] = node['platform'] == 'raspbian' ? 'http://nginx.org/packages/debian' : default['nginx']['upstream_repository']`

I'll try and make a pull request to fix this

**Comment by tas50** [comment]
@PierreBeucher We currently only support platforms that we can test within Test Kitchen either using Vagrant or Dokken images. This allows us to have full CI for each PR and is critical to not just supporting a platform at a point in time, but maintaining that support over time. We don't have any way to continue testing Raspbian support and thus I can't accept a new platform for this cookbook. You can either handle the repo setup in a wrapper cookbook or set the attributes directly.
