### ISSUE TITLE
Proper Passenger/Module install steps?

### ISSUE THREAD

**Issue by TemporarilyOffline** [chef-cookbooks/chef_nginx#114]
### Cookbook version
6.2.0

### Chef-client version
13.4.24

### Platform Details
test-kitchen running ubuntu 17.04

### Scenario:
get passenger installed

### Steps to Reproduce:
That's my question.  I'm trying to sort out the proper way to get nginx+passenger+ssl installed

attributes/default.rb:
```
default['nginx']['repo_source'] = 'passenger'
default['nginx']['passenger']['install_method'] = 'package'
```

recipes/nginx.rb
```
include_recipe 'chef_nginx::passenger'
include_recipe 'chef_nginx'
```

### Expected Result:
Nginx starts and doesn't complain that passenger is missing.

### Actual Result:
Nginx says that it doesn't understand the `passenger_root` directive in my config file.

The docs are unclear to me, what is the proper way to add passenger and nginx to my node?

**Comment by iennae** [comment]
Please be advised that this cookbook has been merged back to https://github.com/chef-cookbooks/nginx.

Based on what you are doing it looks like you are missing 

node['nginx']['package_name'] - 'nginx-extras'

Also in terms of ordering the chef_nginx recipe should be first.

I'm in the process of verifying that this works on ubuntu 17.04 and will update once the box downloads.

**Comment by TemporarilyOffline** [comment]
I added:

```
default['nginx']['package_name'] = 'nginx-extras'
```
to attributes/default.rb and did a `kitchen destroy && kitchen converge` and received the same results.

I also tried to remove chef_nginx in favor of `'nginx', '2.7.6'` and got worse results.  Is `nginx` 3.x branch ready for primetime yet?

**Comment by iennae** [comment]
the nginx cookbook is up to version 7. You should try that one.

**Comment by iennae** [comment]
Hi,

This cookbook will be deprecated in favor of the nginx cookbook. https://github.com/chef-cookbooks/nginx.Please open up an issue on that cookbook https://github.com/chef-cookbooks/nginx/issues.

Thanks.
