### ISSUE TITLE
Cloning resource attributes for service[nginx] from prior resource (CHEF-3694)

### ISSUE THREAD

**Issue by runningman84** [chef-cookbooks/chef_nginx#18]
I hope this new cookbook will finally solve this:

```
         Cloning resource attributes for service[nginx] from prior resource (CHEF-3694)
       Previous service[nginx]: /tmp/kitchen/cache/cookbooks/chef_nginx/recipes/package.rb:47:in `from_file'
       Current  service[nginx]: /tmp/kitchen/cache/cookbooks/chef_nginx/recipes/default.rb:24:in `from_file' at 1 location:
           - /tmp/kitchen/cache/cookbooks/chef_nginx/recipes/default.rb:24:in `from_file'

```

**Comment by iennae** [comment]
@runningman84 thanks for opening this up. Just wanted to paste more of the error that you're talking about for others who might read this issue.

<description>
       Deprecated features used!
         Cloning resource attributes for template[/etc/nginx/sites-available/default] from prior resource (CHEF-3694)
       Previous template[/etc/nginx/sites-available/default]: /tmp/kitchen/cache/cookbooks/chef_nginx/recipes/commons_conf.rb:29:in `from_file'
       Current  template[/etc/nginx/sites-available/default]: /tmp/kitchen/cache/cookbooks/chef_nginx/definitions/nginx_site.rb:25:in `block in from_file' at 1 location:
           - /tmp/kitchen/cache/cookbooks/chef_nginx/definitions/nginx_site.rb:25:in `block in from_file'
         Cloning resource attributes for service[nginx] from prior resource (CHEF-3694)
       Previous service[nginx]: /tmp/kitchen/cache/cookbooks/chef_nginx/recipes/package.rb:47:in `from_file'
       Current  service[nginx]: /tmp/kitchen/cache/cookbooks/chef_nginx/recipes/default.rb:24:in `from_file' at 1 location:
           - /tmp/kitchen/cache/cookbooks/chef_nginx/recipes/default.rb:24:in `from_file'
</description>

**Comment by lamont-granquist** [comment]
yep, :+1: i'm seeing this in lamont-ci

**Comment by genslein** [comment]
There was also a chefspec that covered this issue: https://github.com/sethvargo/chefspec/issues/464

**Comment by tas50** [comment]
This has been fixed on master
