### ISSUE TITLE
Passenger recipe incorrectly adds "/src/nginx_module" to passenger root config

### ISSUE THREAD

**Issue by akshah123** [chef-cookbooks/chef_nginx#19]
Hello,

I am specifying the root for passenger installation as something like

`/home/vagrant/.rvm/gems/ruby-2.2.3/gems/passenger-5.0.30`

However, cookbook sets the value as following:

`passenger_root /home/vagrant/.rvm/gems/ruby-2.2.3/gems/passenger-5.0.30/src/nginx_module;`

I think the problem is the line 47 & 48 here: https://github.com/chef-cookbooks/chef_nginx/blob/master/recipes/passenger.rb#L47

Operator `<<` also adds `/src/nginx_module` to the root value.  This is of course doesn't work for passenger version 5.0.19 and above.

**Comment by tas50** [comment]
@akshah123 Can you open a PR with what you believe is the correct behavior there?

**Comment by akshah123** [comment]
@tas50 sure. I think the fix is as simple as switching from `<<` operator to `+=`.

**Comment by tas50** [comment]
Fixed in 3.1.0
