### ISSUE TITLE
Unable to pick latest installation (1.10.1) on AWS AMI 

### ISSUE THREAD

**Issue by hijklmno** [chef-cookbooks/chef_nginx#21]
Hi guys,

Awesome stuff guys! Thanks for taking over the old nginx cookbook.

Running the cookbook works flawlessly, but the installed nginx version is stuck on 1.8.1. I even tried:
```
"nginx": {
    "version": "1.10.1"
  }
```

As of now AWS's yum repo is stuck on 1.8.1, which seems to be the repo the cookbook ends up using. Is it possible to download and build from source if detected latest build on yum is not the specified one, since the .tar.gz all follow a standard naming convention (eg. `http://nginx.org/download/nginx-node['nginx']['version'].tar.gz`)? I know that AWS's AMI aren't listed in the supported platform, but seeing that AMI is a derivative of RHEL, I wanted to see if this was worth a shot.

Thanks again!

**Comment by tas50** [comment]
Try including the chef_nginx::repo recipe first to setup the nginx repo. Otherwise you're limited to whatever ships with your distro. Feel free to open this back up if that doesn't solve the problem.
