### ISSUE TITLE
ohai plugin bad parsing with --param foo=bar in cc-opt

### ISSUE THREAD

**Issue by szymonpk** [chef-cookbooks/chef_nginx#24]
If configure flags as below are used

```
node.override["nginx"]["configure_flags"]  = [
  "--with-http_gunzip_module",
  "--with-threads",
  "--with-stream",
  "--with-stream_ssl_module",
  "--with-file-aio",
  "--with-openssl=/usr/src/ssl",
  "--with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2'",
  "--with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed'"
]
```

Ohai plugin can't handle [parsing](https://github.com/chef-cookbooks/chef_nginx/blob/ab09256c79dc3db4195f402dffecc7ef311cb104/templates/default/plugins/ohai-nginx.rb.erb#L67) properly, `--with-cc-opt` is split into two elements because of `--params` inside, there is no short call for `--params`, thus it breaks `chef_nginx::source`, because [configure arguments are never equal to configure_flags](https://github.com/chef-cookbooks/chef_nginx/blob/master/recipes/source.rb#L99) and nginx is recompiled with EACH chef run.

Any idea what we can do with this? Whitelisting `--params`?

**Comment by tas50** [comment]
Could we potentially split on --with?

**Comment by tas50** [comment]
I think we can just change the regex to \s--(?!param) to avoid this particular issue. It won't prevent all the potential issues though.
