### ISSUE TITLE
Remove the guard (not_if) from package[nginx]

### ISSUE THREAD

**Issue by daharon** [chef-cookbooks/chef_nginx#26]
### Cookbook version
3.1.1

### Platform Details
CentOS

### Scenario:
```ruby
default[:nginx][:repo_source] = 'nginx'  # Use the Nginx Stable repository.
default[:nginx][:version]     = '1.10.2-1.el6.ngx'
```
I am using the Nginx Yum repository to install Nginx.
I also specify the version to install and use it in my wrapper cookbook like so:
```ruby
edit_resource!(:package, node[:nginx][:package_name]) do
  version node[:nginx][:version]
  not_if  { false }  
end
```
I do not want the `not_if` guard present, because if I change the version in
the attributes, I want it to be installed on my nodes.
The `not_if` guard prevents this.
Further, overriding the guard is not possible.  The result of the block above is
the following resource:
```ruby
yum_package("nginx") do
  package_name "nginx"
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :package
  cookbook_name "chef_nginx"
  recipe_name "package"
  options "--disablerepo=* --enablerepo=nginx"
  version "1.10.2-1.el6.ngx"
  flush_cache {:before=>false, :after=>false}
  not_if "which nginx"
  not_if { #code block }
end
```
Notice that there are now two `not_if` guards.

### Proposal:
Remove the guard on `'package[nginx]'` in `nginx::package`, [here](https://github.com/chef-cookbooks/chef_nginx/blob/v3.1.1/recipes/package.rb#L44).

1. It prevents setting a package version properly.
2. The reason for adding it in the first place is unclear ([link](https://github.com/chef-cookbooks/chef_nginx/commit/dd72e38ff8b0f8ec06cc09672df112a2361d919a#diff-163489655b6e83a317b629e3776fdd7c)).
3. It appears to not serve a purpose, since the provider checks for currently installed packages, anyway ([link](https://github.com/chef/chef/blob/v12.16.15/lib/chef/provider/package/yum.rb#L194)).

**Comment by daharon** [comment]
The `freebsd_package` resource also appears to check for installed versions ([link](https://github.com/chef/chef/blob/v12.16.15/lib/chef/provider/package/freebsd/base.rb#L76)).

Testing in Kitchen with the `which nginx` guard **removed**:

* FreeBSD 9.3
    * 1st run:   
    ```
    Recipe: chef_nginx::package
      * freebsd_package[www/nginx] action install
        - install version 1.10.1_2,2 of package www/nginx
    ```
    * 2nd run:
    ```
    Recipe: chef_nginx::package
      * freebsd_package[www/nginx] action install (up to date)
    ```
* FreeBSD 10.3
    * 1st run:
    ```
    Recipe: chef_nginx::package
      * freebsd_package[www/nginx] action install
        - install version 1.10.1_2,2 of package www/nginx
    ```
    * 2nd run:
    ```
    Recipe: chef_nginx::package
      * freebsd_package[www/nginx] action install (up to date)
    ```

**Comment by rmoriz** [comment]
Please consider bumping the "minor" version next time. This breaks some use cases…
