### ISSUE TITLE
pagespeed depends on non-existent pcre-dev on rhel

### ISSUE THREAD

**Issue by pamri** [chef-cookbooks/chef_nginx#29]
### Cookbook version
3.1.1

### Chef-client version
12.14.1

### Platform Details
CentOS Linux release 7.2.1511 (Core) on OpenStack

### Scenario:
Installing on source on Centos using pagespeed_module fails. attributes/pagespeed has this : 

> default['nginx']['pagespeed']['packages']['rhel'] = %w(pcre-dev pcre-devel zlib-devel)

pcre-dev should be removed from the packages list since it does not exist on rhel systems.

### Steps to Reproduce:
Build from source on Centos. Include pagespeedmodule

### Expected Result:
Installation happens without any errors.

### Actual Result:
>  * No candidate version available for pcre-dev

**Comment by tas50** [comment]
Is there an equivalent package on RHEL or is this truly not needed?

**Comment by pamri** [comment]
Sorry, I forgot to add pcre-dev is redundant since pcre-devel is the right package and  is already defined in the same line.

**Comment by tas50** [comment]
Fixed in master. Thanks for the report
