### ISSUE TITLE
nginx service does not restart/reload on nginx_site change

### ISSUE THREAD

**Issue by flatrocks** [chef-cookbooks/chef_nginx#30]
A wrapper recipe like this:
```ruby
include_recipe 'chef_nginx::default'

# to avoid confusion with this example
node.override['nginx']['default_site_enabled'] = false

nginx_site 'test-site' do
  template 'test-site.erb'
  # Contrived example, to change with each chef run...
  variables response_text: Time.now.strftime('%d/%m/%Y %H:%M:%S')
  enable true
end
```
With this template:
```
server {
  listen 80;
  server_name _;
  location = / {
    add_header Content-Type text/plain;
    access_log off;
    return 200 '<%= @response_text %>';
  }
}
```
... results in __/etc/nginx/sites-enabled/test-site__ like this:
```
server {
  listen 80;
  server_name _;
  location = / {
    add_header Content-Type text/plain;
    access_log off;
    return 200 '25/10/2016 17:58:55';
  }
}
```
A web request to this site returns the expected result, which in this case is static text describing
the time when the chef run occurred, for example "25/10/2016 17:58:55".

Running the converge again at a later time changes the 
__/etc/nginx/sites-enabled/test-site__ file, perhaps to this:
```
server {
  listen 80;
  server_name _;
  location = / {
    add_header Content-Type text/plain;
    access_log off;
    return 200 '25/10/2016 18:01:01';
  }
}
```
But after the chef run, a web request still returns "25/10/2016 17:58:55" indicating that nginx has not noticed the change in the site file.

After manually running `sudo service nginx restart` from the console, the same request will return the expected value of '25/10/2016 18:01:01' indicating nginx is now using the updated site file.

I would expect changes to an nginx_site to take effect immediately on the affected nginx server.

* chef_nginx (3.1.2)
* Chef Development Kit Version: 0.18.30
* chef-client version: 12.15.19
* berks version: 5.1.0
* kitchen version: 1.13.2

**Comment by tas50** [comment]
Fixed in master now
