### ISSUE TITLE
Module headers_more not installed and command nginx not available

### ISSUE THREAD

**Issue by jkulak** [chef-cookbooks/chef_nginx#31]
### Cookbook version

3.1.2
### Chef-client version

12.15.19
### Platform Details

Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-100-generic x86_64) - ubuntu/trusty64
### Scenario:

Install Nginx from source with headers_more_module enabled
### Steps to Reproduce:

my Vagrantfile

``` Ruby
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.berkshelf.enabled = true
    config.omnibus.chef_version = :latest
    config.vm.provision "chef_solo" do |chef|
        chef.json = {
            "nginx" => {
                "install_method" => "source",
                "default" => { "modules" => ["headers_more_module"] }
            }
        }
        chef.run_list = [ "recipe[chef_nginx::default]" ]
    end
end
```

my Berksfile

``` bash
source 'https://supermarket.chef.io'

cookbook 'build-essential'
cookbook 'ohai', '>= 4.1.0'
cookbook 'yum-epel'
cookbook 'runit', '>= 1.6.0'
cookbook 'compat_resource', '>= 12.14.6'
cookbook 'zypper'
cookbook 'chef_nginx', '3.1.2'
```
1. Have chef, berks and vagrant installed on your machine
2. Put above files in one directory and run `$ vagrant up`.
### Expected Result:
- I have an installed Nginx with module headers_more enabled and working
- `$ nginx -V` lists all the configured modules
### Actual Result:

`$ vagrant up` full output: https://gist.github.com/jkulak/58bd033c1faa7aebbefd64f2caa98abb

``` bash
# same result with sudo
vagrant@vagrant-ubuntu-trusty-64:~$ nginx -V
The program 'nginx' can be found in the following packages:
 * nginx-core
 * nginx-extras
 * nginx-full
 * nginx-light
 * nginx-naxsi
Ask your administrator to install one of them
```

Nginx is up and running:

``` bash
vagrant@vagrant-ubuntu-trusty-64:~$ service nginx status
nginx start/running, process 11493
```

I can restart it:

``` bash
vagrant@vagrant-ubuntu-trusty-64:~$ sudo service nginx restart
nginx stop/waiting
nginx start/running, process 11637
```

Now, I'm adding `more_clear_headers Server;` to `/etc/nginx/nginx.conf` and trying to restart nginx:

``` bash
vagrant@vagrant-ubuntu-trusty-64:~$ sudo service nginx restart
nginx stop/waiting
start: Job failed to start
```

I head to check the logs, but:

``` bash
root@vagrant-ubuntu-trusty-64:/var/log/nginx# cat error.log
root@vagrant-ubuntu-trusty-64:/var/log/nginx# ll
total 8
drwxr-x---  2 www-data root   4096 Oct 26 15:44 ./
drwxrwxr-x 11 root     syslog 4096 Oct 26 15:42 ../
-rw-r--r--  1 root     root      0 Oct 26 15:44 access.log
-rw-r--r--  1 root     root      0 Oct 26 15:44 error.log
-rw-r--r--  1 root     root      0 Oct 26 15:44 localhost.access.log
```

**Comment by iennae** [comment]
Hi,

This cookbook will be deprecated in favor of the nginx cookbook. https://github.com/chef-cookbooks/nginx. If this is still an issue for you please open up an issue on that cookbook https://github.com/chef-cookbooks/nginx/issues.

Thanks.
