### ISSUE TITLE
test-kitchen test fails for chef_nginx::package

### ISSUE THREAD

**Issue by gmccue** [chef-cookbooks/chef_nginx#43]
I'm having issues with failing tests since migrating to `chef_nginx` and `ubuntu 16.04`. I believe this may be because `ubuntu 16.04` uses `systemd` by default. This can be configured for the `source` recipe, but not the `package` recipe.

I can submit a PR to fix this if anyone can verify that this is indeed the likely culprit.

### Cookbook version
`4.0.1`

### Chef-client version
`12.16.42`

### Platform Details
OSX with `kitchen-docker`

### Scenario:
Running an integration test (with `test-kitchen`) against a recipe that includes `chef_nginx::default`.

### Steps to Reproduce:
Create a `test-kitchen` test using `kitchen-docker` and `ubuntu 16.04` that calls `chef_nginx::default`

### Expected Result:
A passing test.

### Actual Result:
```sh
...

ERROR: service[nginx] (chef_nginx::package line 46) had an error: Errno::ENOENT: No such file or directory - /sbin/status
```

**Comment by tas50** [comment]
@gmccue 

Are you using the included .kitchen.docker.yml file with kitchen dokken?

**Comment by gmccue** [comment]
This was happening during the testing of my own wrapper cookbook, but it seems to be working properly now. Thanks!

**Comment by wbotelhos** [comment]
I having the same error.

`Ubuntu 16.04.2 LTS`
`chef_nginx (6.1.1)`

I couldn't find any reference to `/sbin/status` on recipe. :/
