### ISSUE TITLE
including http modules only works from the attribute

### ISSUE THREAD

**Issue by axos88** [chef-cookbooks/chef_nginx#45]
### Cookbook version
4.0.1

### Chef-client version
12.6

### Platform Details

n/a

### Scenario:

Including the cookbook's http_module recipes does not work directly. only when added to the modules node attributes

### Steps to Reproduce:

See above

### Expected Result:

It should install the included modules

### Actual Result:

The flags are not added to the configure flags due to the runstate being deleted after the source cookbook runs: https://github.com/chef-cookbooks/chef_nginx/blob/2d47b005a227ca7bf3cd0e8da1495c17f6f661d7/recipes/source.rb#L177

(The runstate is initialized at the start of the same recipe)

Removing those offending lines should make it possible for recipes running after the source recipe to modify the runstate.

**Comment by axos88** [comment]
or the recipes should be renamed by prepending a _ to mark that they should NOT be included directly.

**Comment by iennae** [comment]
Hi,

This cookbook will be deprecated in favor of the nginx cookbook. https://github.com/chef-cookbooks/nginx. If this is still an issue for you please open up an issue on that cookbook https://github.com/chef-cookbooks/nginx/issues.

Thanks.
