### ISSUE TITLE
Including * is unsafe and not recommended. 

### ISSUE THREAD

**Issue by axos88** [chef-cookbooks/chef_nginx#47]
### Cookbook version
4.0.1

### Chef-client version

12.16.15

### Platform Details

debian, but n/a 

### Scenario:

Including * is unsafe and not recommended.  (sites-enabled/*)

Also breaks on windows, to which I am currently working on adding support.

https://github.com/miketheman/nginx/blob/a83f963cdae914effb159a900f45f125ef2e4afc/templates/default/nginx.conf.erb#L31

See also: https://trac.nginx.org/nginx/ticket/1144

**Comment by tas50** [comment]
I'm open to a better way to handle this, but given people rely on wrapper cookbooks a lot this could get pretty gnarly.

**Comment by axos88** [comment]
*.conf, and bump a major version to mark the backward incompatibility.

**Comment by axos88** [comment]
Also AFAIK the wrapper cookbooks use the custom resource defined in this cookbook to define new sites, so that could be adjusted to append the .conf suffix, which would resolve the breakage for a lot of cases

**Comment by iennae** [comment]
Hi,

This cookbook will be deprecated in favor of the nginx cookbook. https://github.com/chef-cookbooks/nginx. If this is still an issue for you please open up an issue on that cookbook https://github.com/chef-cookbooks/nginx/issues.

Thanks.
