### ISSUE TITLE
Nginx installed in wrong directory path name

### ISSUE THREAD

**Issue by drahamim** [chef-cookbooks/chef_nginx#52]
### Cookbook version 
chef_nginx (4.0.2)

### Chef-client version  
12.16.42

### Platform Details
Test-Kitchen w/ Docker using ubuntu:14.04

### Scenario:
Install Nginx from source with PageSpeed module

### Steps to Reproduce:

run cookbook as such:

```node.override['nginx']['install_method'] = 'source'
node.override['nginx']['source']['version'] = '1.11.5'
node.override['nginx']['source']['modules'] = %w(chef_nginx::pagespeed_module)
node.override['nginx']['source']['checksum'] = '223f8a2345a75f891098cf26ccdf208b293350388f51ce69083674c9432db6f6'
#node.override['nginx']['source']['prefix'] = "/opt/nginx-#{node['nginx']['source']['version']}"
node.override['nginx']['source']['sbin_path'] = "#{node['nginx']['source']['prefix']}/sbin/nginx"
node.override['nginx']['source']['url'] = "http://nginx.org/download/nginx-#{node['nginx']['source']['version']}.tar.gz"

include_recipe 'chef_nginx::source'
```

### Expected Result:

Nginx v 1.11.5 installed with pagespeed module in /opt/nginx-1.11.5/

### Actual Result:
Nginx 1.11.5 installed with pagespeed in /opt/nginx-1.10.1

**Comment by Sauraus** [comment]
@drahamim I believe you missed one final derived attribute
```
default['nginx']['source']['default_configure_flags'] = %W(
  --prefix=#{node['nginx']['source']['prefix']}
  --conf-path=#{node['nginx']['dir']}/nginx.conf
  --sbin-path=#{node['nginx']['source']['sbin_path']}
)
```

That's what is being passed into the `configure && make && make install` block.

**Comment by tas50** [comment]
@Sauraus is right here. Derived attributes are pretty awful and this requires setting both attributes. If we could do it all over we'd do it differently, but this was all before my time.
