### ISSUE TITLE
Nginx service is not running on Ubuntu14 (nginx.org package)

### ISSUE THREAD

**Issue by armab** [chef-cookbooks/chef_nginx#57]
Creating an Issue from the https://github.com/chef-cookbooks/chef_nginx/pull/55#issuecomment-266117889 for better tracking.

When using this cookbook with nginx.org package-based installation, `service nginx status` is reported as `stopped` under `Ubuntu Trusty`: 
![](https://camo.githubusercontent.com/ada88d8ad70a21367d3e99b11939cdb612691352/68747470733a2f2f692e696d6775722e636f6d2f426634464877712e706e67)

Some details discovered: 
- `sudo service nginx status` reports "not running"
- `nginx` process is running, 80 port is bound
- `sudo service nginx restart` failing, because 80 port is already in use
- `/var/run/nginx.pid` doesn't exist so nginx reports wrong status
- after killing `nginx` manually and restarting nginx service everything works as expected
- it happens only on first install _with_ this cookbook

If I install the same `nginx` package manually _without_ this cookbook on a fresh node, - it works OK and service is started, so I assume something wrong is happening inside the cookbook along the way.
This is _not_ a Docker-related issue, I tested in Ubuntu Trusty VM as well.

I see this behavior in both cookbook version `v5.0.0` and latest `master`.
Your Travis build with Docker shows the same failure: https://travis-ci.org/chef-cookbooks/chef_nginx/builds/182913979.

**Comment by tas50** [comment]
I'm putting together a PR to fix this. The same issue is hitting Debian 8 systems as well.

Also this is a beautiful issue you filed here. Thanks for spelling it all out nicely.

**Comment by tas50** [comment]
@armab I've reworked how the pidfile is determined using a helper method instead of the previous attribute. This should handle the scenario of newer Debian/Ubuntu releases, but also using the upstream repos, which use the older pidfile location. This was released in 5.0.1. Let me know if it solves your problem.

**Comment by armab** [comment]
@tas50 Confirming that fix worked :+1: 

Thank you for your hard work maintaining this repo!
