### ISSUE TITLE
Default site not disabled on Ubuntu

### ISSUE THREAD

**Issue by mmarschall** [chef-cookbooks/chef_nginx#62]
### Cookbook version
5.0.1

### Chef-client version
12.17.44

### Platform Details
ubuntu 16.04 x86_64

### Scenario:
I set `node['nginx']['default_site_enabled']` to `false` but the default site is enabled through `/etc/nginx/conf.d/default.conf`

### Steps to Reproduce:
My recipe includes:

```
node.override['nginx']['default_site_enabled'] = false
include_recipe "chef_nginx::default"

```
### Expected Result:
The default site should not be enabled.

### Actual Result:
While the default site is not enabled via `/etc/nginx/sites-enabled/default`, the file `/etc/nginx/conf.d/default.conf` is still there enabling the default site.

[The `commons_dir` recipe](https://github.com/chef-cookbooks/chef_nginx/blob/master/recipes/commons_dir.rb#L46) only deletes `/etc/nginx/conf.d/default.conf` on platform families `rhel` and `fedora`. The file should be deleted on Ubuntu as well.

If I add 

```
if !node['nginx']['default_site_enabled']
  file "/etc/nginx/conf.d/default.conf" do
    action :delete
  end
end

```
to my recipe, everything works as expected.

**Comment by rhass** [comment]
The issue appears to be caused by the nginx.org version of the package which installs the default site into `/etc/nginx/conf.d/default.conf`.

**Comment by tas50** [comment]
https://github.com/chef-cookbooks/chef_nginx/pull/65 should fix this by having a 1 off workaround for disabling the default site.

**Comment by mmarschall** [comment]
Works perfectly. Thanks a lot!

An idea when you'll release it?
