### ISSUE TITLE
nginx_site template does not accept file specificity for template parameter.

### ISSUE THREAD

**Issue by erenfro** [chef-cookbooks/chef_nginx#71]
### Cookbook version
5.0.7

### Chef-client version
12.18.31

### Platform Details
CentOS 7.3.1611

### Scenario:
When setting the template parameter in the nginx_site resource, it only accepts String, but not like other template specificity, not an array like the template resource's source parameter.

### Steps to Reproduce:
```
nginx_site "name" do
  template %W{
    nginx/#{node['platform']}/#{node['platform_version'].to_i}/name.conf.erb
    nginx/#{node['platform']}/name.conf.erb
    nginx/#{node['platform_family']}/#{node['platform_version'].to_i}/name.conf.erb
    nginx/#{node['platform_family']}/name.conf.erb
    default/name.conf.erb
    name.conf.erb
}
```

### Expected Result:
The recipe would determine first-matching file in the array and use it as the template just like the template resource would do.

### Actual Result:
```
ERROR: Property template must be one of: String!  You passed ["nginx/centos/7/name.conf.erb", "nginx/centos/name.conf.erb", "nginx/rhel/7/name.conf.erb", "nginx/rhel/name.conf.erb", "default/name.conf.erb", "name.conf.erb"].
```

**Comment by tas50** [comment]
Thanks for the report. I fixed this on master by allowing template to be an array and I'll be releasing it as soon as Travis runs.

**Comment by erenfro** [comment]
Very awesome! Thank you very much. I've been using various methods of source file organization as of late, and honestly think it's a really good idea to allow implementation of it, especially for things using resource providers like this.
