### ISSUE TITLE
ngx_lua_module compilation does include path to output library causing nginx not to start

### ISSUE THREAD

**Issue by Sauraus** [chef-cookbooks/chef_nginx#81]
### Cookbook version
5.1.1

### Chef-client version
12.19

### Platform Details
CentOS 6.x, 7.x Ubuntu 14.x, 16.x etc.

### Scenario:
Include the LUA module by building from source.

### Steps to Reproduce:
Set the following attribute in your wrapper cookbook and build from source
```
default['nginx']['source']['modules']  = %w(
  chef_nginx::ngx_lua_module
)
```

### Expected Result:
nginx is built from source and includes the libluajit library and is able to start

### Actual Result:
nginx fails to start because `/lib64/libluajit-5.1.so.2` does not exist, the `lua.rb` recipe declares this `export LUAJIT_LIB="/usr/local/lib"` at build time resulting in the lib ending up here `/usr/local/lib/libluajit-5.1.so.2`

**Comment by Sauraus** [comment]
My proposal is to fix this by adding this to the `lua.rb` recipe:
```
node.run_state['nginx_configure_flags'] =
    node.run_state['nginx_configure_flags'] | ['--with-ld-opt="-Wl,-rpath,/usr/local/lib"']
```

**Comment by Sauraus** [comment]
PR Incoming as soon as my team merges it into our fork :) https://github.com/Roblox/chef_nginx/pull/1

**Comment by tas50** [comment]
Fixed and released
