### ISSUE TITLE
Borked runit support

### ISSUE THREAD

**Issue by gionn** [chef-cookbooks/chef_nginx#82]
### Cookbook version
5.1.1

### Chef-client version
chef-solo 12.6.0

### Platform Details
Ubuntu 14.04

### Scenario:
Migrating from miketheman/nginx  cookbook without switching from runit to upstart (will do later)

### Steps to Reproduce:
init_style to runit

### Expected Result:
Converge success

### Actual Result:

```
           ================================================================================
           Error executing action `enable` on resource 'service[nginx]'
           ================================================================================
           
           Chef::Exceptions::UnsupportedAction
           -----------------------------------
           #<Chef::Provider::Service::Simple:0x0000000665e810> does not support :enable
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/chef_nginx/recipes/source.rb
           
           114:   service 'nginx' do
           115:     supports       status: true, restart: true, reload: true
           116:     reload_command "#{node['runit']['sv_bin']} hup #{node['runit']['service_dir']}/nginx"
           117:     action         [:start, :enable]
           118:   end
           119: when 'upstart'
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/chef_nginx/recipes/source.rb:114:in `from_file'
           
           service("nginx") do
             provider Chef::Provider::Service::Simple
             action [:start, :enable]
             supports {:status=>true, :restart=>true, :reload=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "nginx"
             running true
             pattern "nginx"
             start_command "/usr/bin/sv start /etc/service/nginx"
             stop_command "/usr/bin/sv stop /etc/service/nginx"
             status_command "/usr/bin/sv status /etc/service/nginx"
             restart_command "/usr/bin/sv restart /etc/service/nginx"
             reload_command "/usr/bin/sv hup /etc/service/nginx"
             declared_type :service
             cookbook_name :chef_nginx
             recipe_name "source"
           end
```

**Comment by cheeseplus** [comment]
What version of the runit cookbook are you using? `:enable` is an action in recent versions - that's also a reasonably old version of Chef (over a year) so testing both on latest would be ideal.

**Comment by gionn** [comment]
My Berksfile.lock state `runit (3.0.5)`, but AFAIK looking the stacktrace, the missing `:enable` action is in `<Chef::Provider::Service::Simple>`, and if I take a look at the current chef master:

https://github.com/chef/chef/blob/master/lib/chef/provider/service.rb
https://github.com/chef/chef/blob/master/lib/chef/provider/service/simple.rb

there isn't any `:enable` method for such provider.

Then, looking at https://github.com/chef-cookbooks/chef_nginx/commit/e9d518a3c6494e39d49f63f538c1ba83456fe9c0 I see a refactoring in `recipes/source.rb` (probably without test coverage) that introduces this bug.

**Comment by tas50** [comment]
Version 6.0 of this cookbook removed support for Runit so there's no need for this change anymore. I'd highly recommend moving away from Runit and using a modern init system such as Upstart or Systemd instead.

**Comment by gionn** [comment]
@tas50 we have a bunch of nodes running nginx via runit, do you have some suggestions for a migration path to upstart?

Thanks.

**Comment by tas50** [comment]
We don't at the moment, but I should get some cleanup code in there. We've done that in other cookbooks that used runit.
