### ISSUE TITLE
Feature Request: Automated Testing for passenger

### ISSUE THREAD

**Issue by klyonrad** [chef-cookbooks/chef_nginx#92]
I noticed that the passenger install is not included in the Test Suite. Is there a reason for that?

Would the addition be welcomed as a pull request?

**Comment by iennae** [comment]
There isn't a specific reason for not having a test. Having tests in general is greatly appreciated. Pull requests are always welcome. Thanks!

**Comment by klyonrad** [comment]
I quickly made the Pull Request. Unsurprisingly the tests are not running through an all platforms (see issue #88 )

So for this Pull Request: should we simply exclude the not working platforms in the `kitchen.yml` at the current state and write it as a TODO?

Any other improvement suggestions or functional requirements are welcome of course :)
