### ISSUE TITLE
Using repo_passenger to install nginx and passenger fails.

### ISSUE THREAD

**Issue by tisbeok** [chef-cookbooks/chef_nginx#94]
### Cookbook version
6.0.1

### Chef-client version
12.19.36

### Platform Details
Ubuntu 16.04.2 on AWS

### Scenario:
I am trying to install nginx and passenger using the repo_passenger recipe.

### Steps to Reproduce:
I am assigning a role to my EC2 instance. Right now the role just includes one cookbook. In the default recipe for that cookbook, I have included the following lines to install nginx and passenger:

```
if node.platform_family == 'debian'
  include_recipe 'chef_nginx::repo_passenger'
else
  include_recipe 'chef_nginx::passenger'
end
```

### Expected Result:
I expect nginx and then passenger to installed by the following lines in chef_nginx::passenger:
```
if node['nginx']['passenger']['install_method'] == 'package'
  package node['nginx']['package_name']
  package 'passenger'
```

I have not specified any attributes, so the cookbook should be using the default package install method.

### Actual Result:
From my understanding, the resources in chef recipes are supposed to execute in the order specified. However, chef tries to execute the template resource in chef_nginx::passenger before the package installs, even though the template is the last resource declared. The nginx conf.d directory does not exist yet since nginx has not been installed, so the chef run fails:
```

  * template[/etc/nginx/conf.d/passenger.conf] action create[2017-04-18T17:49:53+00:00] INFO: Processing template[/etc/nginx/conf.d/passenger.conf] action create (chef_nginx::passenger line 58)

    * Parent directory /etc/nginx/conf.d does not exist.
    ================================================================================
    Error executing action `create` on resource 'template[/etc/nginx/conf.d/passenger.conf]'
    ================================================================================
    
    Chef::Exceptions::EnclosingDirectoryDoesNotExist
    ------------------------------------------------
    Parent directory /etc/nginx/conf.d does not exist.
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/chef_nginx/recipes/passenger.rb
    
     58: template "#{node['nginx']['dir']}/conf.d/passenger.conf" do
     59:   source 'modules/passenger.conf.erb'
     60:   notifies :reload, 'service[nginx]', :delayed
     61: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/chef_nginx/recipes/passenger.rb:58:in `from_file'
    
    template("/etc/nginx/conf.d/passenger.conf") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      source "modules/passenger.conf.erb"
      declared_type :template
      cookbook_name "chef_nginx"
      recipe_name "passenger"
      mode nil
      owner nil
      group nil
      path "/etc/nginx/conf.d/passenger.conf"
      verifications []
    end
    
    Platform:
    ---------
    x86_64-linux
    
[2017-04-18T17:49:53+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-04-18T17:49:53+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-04-18T17:49:53+00:00] ERROR: Exception handlers complete
Chef Client failed. 2 resources updated in 05 seconds
[2017-04-18T17:49:53+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-04-18T17:49:53+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-04-18T17:49:53+00:00] ERROR: template[/etc/nginx/conf.d/passenger.conf] (chef_nginx::passenger line 58) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /etc/nginx/conf.d does not exist.
[2017-04-18T17:49:54+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by kjw1** [comment]
I think you're meant to put the modules you want to install in the `node['nginx']['default']['modules']` attribute, then run the default recipe. That should do things in the right order.

**Comment by tas50** [comment]
@tisbeok can you give me the complete output of your chef run.

Also as a side note you shouldn't do node.platform_family. That works technically on Chef 12, but won't work on Chef 13. There's a handy helper you can use there platform_family?('debian') which returns true/false.

**Comment by iennae** [comment]
Hi,

This cookbook will be deprecated in favor of the nginx cookbook. https://github.com/chef-cookbooks/nginx. If this is still an issue for you please open up an issue on that cookbook https://github.com/chef-cookbooks/nginx/issues.

Thanks.
