### ISSUE TITLE
Let repo properties (e.g. signing/gpg key) be configurable 

### ISSUE THREAD

**Issue by iancward** [chef-cookbooks/chef_nginx#95]
### Cookbook version
6.0.1

### Chef-client version
N/A

### Platform Details
N/A

### Scenario:
This cookbook currently support the yum baseurl to be an attribute; however, the gpg key is not an attribute, so you're still not able to use the cookbook behind a firewall that blocks access to the internet.
The suse/zypper repo doesn't use attributes at all, and the debian repository also uses a hard-coded signing key.

Since I support servers that live behind a firewall, it would be nice to be able to use the repo recipe to completely configure the repo recipe to use our internal mirror(s).

**Comment by tas50** [comment]
If you'd like to open a PR to make these configurable that would be great

**Comment by iancward** [comment]
Hi @tas50:
I've got some changes staged locally on my workstation and I've started a contribution approval workflow within my organization for the submission. I'll open a PR when I'm able to (hopefully within the next two weeks).
